services:
  - type: web
    name: asset-management-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./AssetManagementApp.Api/Dockerfile
    autoDeploy: true
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: JWT:Key
        sync: false
      - key: JWT:Issuer
        value: https://asset-management-api.onrender.com
      - key: JWT:Audience
        value: https://asset-management-api.onrender.com
